pipeline:
  docker:
    image: plugins/docker
    username: ${DOCKERHUB_USERNAME}
    password: ${DOCKERHUB_PASSWORD}
    email: ${DOCKERHUB_EMAIL}
    repo: adminfromhell/pushjet
    dockerfile: pushjet/Dockerfile
    build_args:
      - VCS_REF=`git rev-parse --short HEAD` .
    tags:
      - latest
